name: CI

on:
  push:
    paths:
      - ".github/workflows/**"
      - dune
      - dune-project
      - .ocamlformat
      - "**.ml"
      - "**.mli"
  pull_request:
    paths:
      - ".github/workflows/**"
      - dune
      - dune-project
      - .ocamlformat
      - "**.ml"
      - "**.mli"

permissions: read-all

jobs:
  build:
    strategy:
      matrix:
        include:
          - os: ubuntu-latest
            display-name: Linux
            ocaml-version: 5.2.0
            ocaml-compiler: ocaml-variants.5.2.0+options,ocaml-option-flambda
            artifact: descartes-x86_64-linux
          - os: macos-latest
            display-name: macOS
            ocaml-version: 5.2.0
            ocaml-compiler: ocaml-variants.5.2.0+options,ocaml-option-flambda
            artifact: descartes-arm64-darwin
          - os: windows-latest
            display-name: Windows
            ocaml-version: 5.2.0
            ocaml-compiler: ocaml-variants.5.2.0+options,ocaml-option-flambda
            artifact: descartes-x86_64-windows.exe

    runs-on: ${{ matrix.os }}
    name: Build with OCaml ${{ matrix.ocaml-version }} on ${{ matrix.display-name }}

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up OCaml ${{ matrix.ocaml-version }}
        uses: ocaml/setup-ocaml@v3
        with:
          ocaml-compiler: ${{ matrix.ocaml-compiler }}
          dune-cache: true

      - name: Install dependencies
        run: opam install . --deps-only

      - name: Build
        run: opam exec -- dune build --profile release

      - name: Upload the build artifact
        uses: actions/upload-artifact@v4
        with:
          name: ${{ matrix.artifact }}
          path: _build/default/bin/descartes.exe
          retention-days: 1

  lint-doc:
    runs-on: ubuntu-latest
    name: Lint documentation

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up OCaml
        uses: ocaml/setup-ocaml@v3
        with:
          ocaml-compiler: ocaml-variants.5.2.0+options,ocaml-option-flambda
          dune-cache: true

      - uses: ocaml/setup-ocaml/lint-doc@v3

  lint-fmt:
    runs-on: ubuntu-latest
    name: Lint formatting

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up OCaml
        uses: ocaml/setup-ocaml@v3
        with:
          ocaml-compiler: ocaml-variants.5.2.0+options,ocaml-option-flambda
          dune-cache: true

      - uses: ocaml/setup-ocaml/lint-fmt@v3

  lint-opam:
    runs-on: ubuntu-latest
    name: Lint opam

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up OCaml
        uses: ocaml/setup-ocaml@v3
        with:
          ocaml-compiler: ocaml-variants.5.2.0+options,ocaml-option-flambda
          dune-cache: true

      - uses: ocaml/setup-ocaml/lint-opam@v3
